var Promise = require('bluebird');
var db = require('./server/db');
var Review = db.models.review;
var Product = db.models.product;
var Related = db.models.related;

var data = {
  reviews: [
    {"asin": "616719923X", "reviewerName": "Amazon Customer", "reviewText": "Just another flavor of Kit Kat but the taste is unique and a bit different.  The only thing that is bothersome is the price.  I thought it was a bit expensive....", "overall": 4.0, "summary": "Pretty good"},
    {"asin": "616719923X", "reviewerName": "amf0001", "reviewText": "I bought this on impulse and it comes from Japan,  which amused my family,  all those weird stamps and markings on the package. So that was fun.  It said it would take about a month to arrive and it did take that long.  I was hoping for a more interesting taste but to our family,  it just tasted a bit less flavorful or weaker than the standard milk chocolate kit kat.  The green tea flavor was too subtle for the sugar and it just tasted sweet. The wafers were very crispy, and that was good,  but it tasted a bit anemic to us.I'm happy I bought it, but don't need to buy it again.", "overall": 3.0, "summary": "3.5 stars,  sadly not as wonderful as I had hoped"},
    {"asin": "616719923X", "reviewerName": "Caitlin", "reviewText": "Really good. Great gift for any fan of green tea! Just so expensive to purchase candy from across the sea.", "overall": 4.0, "summary": "Yum!"},
    {"asin": "616719923X", "reviewerName": "DebraDownSth", "reviewText": "I had never had it before, was curious to see what it was like. Smooth, great subtle good flavor. I am ordering more and plan to make it a routine.", "overall": 5.0, "summary": "Unexpected flavor meld"},
    {"asin": "616719923X", "reviewerName": "Diana X.", "reviewText": "I've been looking forward to trying these after hearing about how popular they were in Japan, and among Kit Kat fans as well. I do not recommend ordering these during warm weather, because they can melt and become smushy. I ordered mine right when summer began, and they were a bit mushy so I let them solidify under room temp. Afterwards, I tried some and they tasted fine. I was expecting a stronger green tea or matcha flavor, but it is actually quite subtle. The outer coating was creamy and not overly sugary, which I liked. Overall, I wouldn't say it's insanely good, but definitely a yummy treat.", "overall": 4.0, "summary": "Not a very strong tea flavor, but still yummy & creamy!"},
    {"asin": "616719923X", "reviewerName": "Elizabeth", "reviewText": "These Kit-kats are very good, but if you're looking for a strong green tea flavor- you will be disappointed. The green tea flavor is very subtle.", "overall": 4.0, "summary": "Subtle"},
    {"asin": "616719923X", "reviewerName": "Emily Veinglory \"Book Reviewer\"", "reviewText": "I found these in a Mitsuwa Marketplace in Illinois.I actually expected them to taste better than the did.  they were okay but seem smaller than standard kit kats and the taste was a tad mild compared to other green tea candies I have tried.But still, they were pleasant enough and nice for a change.", "overall": 3.0, "summary": "Available in some US stores"},
    {"asin": "616719923X", "reviewerName": "greenlife", "reviewText": "Creamy white chocolate infused with Matcha green tea surrounding layers of wafers. Much less sweeter than the traditional Kitkat. Small size is perfect to satisfy the chocolate craving w/o the guilt. Was in LA last week and picked up a bag on a whim at the Japanese store in Little Tokyo. Now, back in WI and regretting not picking up a handful more. Not only were these Kitkats delicious, the bags were only $5 each!", "overall": 5.0, "summary": "So Delicious!!"},
    {"asin": "616719923X", "reviewerName": "Japhyl", "reviewText": "After hearing mixed opinions about these Kit Kats, I decided to try them. They are excellent, and I do not regret purchasing them at all. They taste like matcha with a bit of a vanilla and milky flavor as well. They are not too sweet or too plain. These are the best Kit Kats I've ever had, and I would recommend them to anyone who likes matcha-flavored candies or anyone wanting to try an unusual kind of Kit Kat.", "overall": 5.0, "summary": "These are my favorite candies ever!"},
    {"asin": "616719923X", "reviewerName": "Jean M \"JM\"", "reviewText": "I love green tea, I love Kit Kats, but the two do not belong together. I hate the after taste of them.", "overall": 1.0, "summary": "Not a fan"},
    {"asin": "616719923X", "reviewerName": "Jeremy", "reviewText": "I ordered these in Summer so they of course arrived melted, a trip the freezer made them awesome again though. Just order them in cooler times of the year and you should get them in good condition.I love these so much more than the regular chocolate Kit-Kat bars. I hope some day to see them on store shelves in the US some day.", "overall": 5.0, "summary": "Amazing!"},
    {"asin": "616719923X", "reviewerName": "M. Magpoc \"maliasuperstar\"", "reviewText": "These are definitely THE BEST candy bar out there!  I just wish I was able to find them in a local store instead of having to buy them online!", "overall": 5.0, "summary": "I wish I could find these in a store instead of online!"},
    {"asin": "616719923X", "reviewerName": "M. Zinn \"mczinn\"", "reviewText": "Yes - this is one of the most expensive candies around, because it only comes imported. But my goodness - are these ever good. The KitKat folks could really clean up if they started selling these in the US. Once you try them you can't wait for more. So yummy and delivered quickly and fresh.", "overall": 5.0, "summary": "Thank goodness they are expensive"},
    {"asin": "616719923X", "reviewerName": "Sabrina", "reviewText": "I love the green tea kitkat, taste so good, not as sweet as the milk chocolate one, and it comes with 12 small pack, easy to keep on a diet, i love this one and the dark chocolate one!", "overall": 5.0, "summary": "it is good"},
    {"asin": "616719923X", "reviewerName": "Sunny", "reviewText": "I love Kit Kat & green tea....together they are okay.  Nothing to get excited about.  I wouldn't order this again.", "overall": 3.0, "summary": "Meh"},
    {"asin": "616719923X", "reviewerName": "The Fallen Angel with a broken Wing \"I Cry Ou...", "reviewText": "I tried this for the first time today and it is delicious but I don't quite taste the Matcha flavor as you would in like say a Green Tea ice cream. To me it tasted like white chocolate with a grainy texture which I'm guessing is the Matcha tea powder. I think my favorite KitKat flavor mix is the Mocha.", "overall": 4.0, "summary": "Not enough Matcha tea flavor for me ... (=_=)"},
    {"asin": "9742356831", "reviewerName": "Cheryl", "reviewText": "I've purchased different curries in the grocery store and was never completely happy with the flavor. I read a recipe that recommended this brand and after using it I can see why they recommend this specific brand. Great flavor - I purchased all 3 - Green, Red, and Yellow curry paste and have enjoyed all 3 types.", "overall": 5.0, "summary": "Great flavor"},
    {"asin": "9742356831", "reviewerName": "GinSing", "reviewText": "I love ethnic foods and to cook them. I recently purchased another product which was a major disappointment, so I was back to the drawing board.The reviews won me over, and free shipping, so I ordered one of each, red and green. Tonight I used the green for the first time and WOW! It made me look like a gourmet international chef - it is so incredibly good!It was definitely hot, though, which is fine with me but I was glad I had the coconut milk base. This is excellent and I will keep this on hand always.", "overall": 5.0, "summary": "OMG! What a treasure find!"},
    {"asin": "9742356831", "reviewerName": "Jennifer Lee", "reviewText": "I started a new diet restricting all added sugars.  This was one of the only brands I could find that didn't have sugar added into the ingredients.  And it tastes great to boot!  I'm not sure I could finish this whole tub before it goes off though.  How long does it last?", "overall": 4.0, "summary": "Tastes great!"},
    {"asin": "9742356831", "reviewerName": "J. Zack", "reviewText": "So many flavors. I can't begin to tell you how much I love all of mae ploy curries. I should ask them for recipes. Basically its a plastic lidded container about the size of I wanna say two and one half yogurts. It has a bag inside that you pull out and inside that clear bag is the curry. Its all mashed in there. I cut a corner and take out  a little at a time. Having the spices mixed and its a paste makes it nicer to make a sauce and marry this flavor to anything. Veggies love it that are steamed, scrambled eggs, rice pasta and even fish and meat.", "overall": 5.0, "summary": "Thai curry is the way to go to add spice to anything"},
    {"asin": "9742356831", "reviewerName": "LindaE", "reviewText": "I've used this a lot recently in some of my chicken dishes. I don't use a lot, I do like spicy foods and a little goes a long way. The plus is its in a bag and you can squeeze out what you need.. Yes I will buy more", "overall": 5.0, "summary": "Thai Green Curry"},
    {"asin": "9742356831", "reviewerName": "Matthew S.", "reviewText": "This is a huge step up in quality from the kind that is normally available in the supermarkets near me. This makes green curry extremely easy. It also appears to have a pretty good shelf life which is good because there's enough in here to make several large portions, so unless you eat green curry all the time it will last quite a while.", "overall": 5.0, "summary": "Make green curry quite easy"},
    {"asin": "9742356831", "reviewerName": "Mike Williams", "reviewText": "I have two things in mind when I make a Thai curry: 1) I want it to taste good and 2) I want whomever I'm making it for to feel like it's fairly authentic. Mae Ploy makes both of these tasks quite easy to accomplish. The very best curry is made from making one's own paste, however finding the time and perhaps even more difficult, the ingredients to do so does not compensate for the difference in taste. In my experience, Mae Ploy is an excellent green curry paste that tastes plenty fresh and will give you that same satisfaction that you get from a Thai restaurant.A few things I've learned using their curry pastes over the years:1) If you are cooking for people who are not used to Thai food, the proportions indicated in the directions on the container will be WAY TOO HOT for them. This is especially true with Green Curry and even more important if there will be children eating the meal. It's very easy to adjust the amount of paste used, and with practice you'll learn just how much is good for the experienced palate and how much is good for kids or newbies.2) The packaging doesn't mention anything about how long the product keeps. The paste comes in a plastic container with a lid that can seal, but it's actually in a thick plastic bag inside that container. I used to cut open the bag and leave it in the container, but I've taken to just cutting a hole in the corner and using it like an icer would in a bakery. I feel like the double container might help it to keep a bit longer. Once the bag is opened, the product should be stored in the refrigerator. There is enough in the container to make several curry dishes.3) Mae Ploy paste is fantastic, but choosing a bad coconut milk can degrade the quality of your dish or even ruin it altogether. Don't go with \"lite\" brands, and look for something more authentic if you can find it. I've found Chaokoh brand comes with a higher amount of cream which gives your curry a more consistent flavor. Chaokoh is the brand most often found in Asian markets and I've always figured that they would know best.This product is incredibly easy to use and turns out a Green Curry that will make your friends think yours is good as a restaurant's. I don't believe there is a better paste on the market and when you factor in the price it's a no brainer. (FYI,If you live in an area where there are asian markets, you will do better buying it there as it will be even cheaper).", "overall": 5.0, "summary": "Authentic, easy, and delicious!"},
    {"asin": "9742356831", "reviewerName": "M. Thompson \"Dyson Diva\"", "reviewText": "I like to make my own curry but this is a tasty alternative.  I use it as a base for all kinds of different curry recipes.", "overall": 5.0, "summary": "Yum!"},
    {"asin": "9742356831", "reviewerName": "Noell Rose", "reviewText": "Because of Mae Ploy Thai Green Curry Paste, green thai curry has become my signature dish. I am always being asked to make it. Remember that it is very spicy so a little goes a long way. The flavors in this paste are complex and varied and make for a delicious curry. We are living overseas (not in Thailand) so I am happy to see that it is available on Amazon!", "overall": 5.0, "summary": "My new signature dish!"},
    {"asin": "9742356831", "reviewerName": "R. Myers", "reviewText": "Hadn't had green curry before so I bought this to give it a try.  Turned out really good and I loved the heat level I got using 2 Tbs of paste.  I ordered the red paste too but haven't gotten to try it yet, but if it's as good at this paste it should be way better than what my grocery store carries.", "overall": 4.0, "summary": "Really good"},
    {"asin": "9742356831", "reviewerName": "serioushopper \"Ely\"", "reviewText": "Being newbie to THai cooking, these are great addition to my kitchen. Its tastes really good for vegetable and chicken curry.", "overall": 5.0, "summary": "Taste great"},
    {"asin": "9742356831", "reviewerName": "S. Thornton \"Tea Freak\"", "reviewText": "I have tried all the curris from Mae Ploy (excluding the Panag) and various other curry pastes out there. Mae Play is a solid and affordable curry paste that keeps. The Red has more heat, but the green has more spice. The Yellow and Matsaman curry paste don't really have any heat to me, but do taste good as well.For a holiday treat, substitute eggnog for coconut milk with the green curry. It is super delicious (just be advised your GI tract WILL hate you later for doing so)", "overall": 5.0, "summary": "Delicious"},
    {"asin": "9742356831", "reviewerName": "Terry Bisgrove \"Mr.E.Man\"", "reviewText": "I like other styles of Mae Ploy curry paste, but the green just doesn't work for me. Overwhelming garlic, no heat, and very bland. I would not purchase this product again.", "overall": 3.0, "summary": "OK Product"},
    {"asin": "9742356831", "reviewerName": "TrishS \"TrishS\"", "reviewText": "I have both the red and green curry paste.  The green is milder.  I use both of them in variety of dishes and often spice up soups and stews that need a little zing.  It is so convient to have them in the frig.", "overall": 5.0, "summary": "Tasty and fast"},
    {"asin": "B0000CCZYY", "reviewerName": "Amazon Customer", "reviewText": "Licorice is my favorite candy, and it promotes good digestion. Since I have some digestive issues, I eat licorice on a regular basis. I've tried basically every brand. I bought this because it's advertised as soft licorice. However, it is the same consistency as the cheapest stuff on the grocery store shelf; the difference is that this has a stronger flavor. The flavor is nice. The consistency and texture is terrible. I bought another package hoping the first was just old/stale, but the next package was the same. I threw away both packages.", "overall": 1.0, "summary": "Not soft at all. Basically same as cheap licorice but with stronger flavor."},
    {"asin": "B0000CCZYY", "reviewerName": "C. Gray", "reviewText": "Nice and soft, super licorice flavor.  I love licorice and have since I was a kid.  This Panda product is very good licorice.", "overall": 5.0, "summary": "Delicious authentic licorice"},
    {"asin": "B0000CCZYY", "reviewerName": "Doug Erlandson", "reviewText": "These soft licorice bites from Panda are not as soft as the &#34;soft-eating licorice&#34; from Down Under but are what I would describe as soft but chewy. They are truly &#34;all natural&#34; and have a minimum of ingredients&#8211;&#8211;molasses, wheat flour, licorice extract, and natural flavor (aniseed oil). Nothing more than that. They have a slightly grainy texture, which comes from the use of wheat flour. They also have a strong, traditional licorice taste, which make them ideal for a person with a craving for genuine licorice.", "overall": 5.0, "summary": "Excellent and healthful"},
    {"asin": "B0000CCZYY", "reviewerName": "D. Pawl \"Dani\"", "reviewText": "I will come clean to you, here and now, and admit that I do have ONE addiction.  That addiction is this totally wonderful Panda licorice.  For starters, it isn't too sweet. Secondly, it is made with anise oil and has a wonderful flavor.  Plus, the blurb on the side of the box is right.  Licorice does have mellowing properties and helps with digestion, and I also notice that I feel less stressed after I eat it.  [Or is this purely psychological?]  It's wonderful for those days when you are craving a treat, but don't want to feel guilty afterwards.  It's fat free and you should definitely keep it in on a high shelf out of reach, or you might find yourself eating the box in just a couple of days!", "overall": 5.0, "summary": "addictive....."},
    {"asin": "B0000CCZYY", "reviewerName": "Lauren Hemedinger", "reviewText": "I have tried other brands and this one is by far the best Licorice on the market today.  Buy it!", "overall": 5.0, "summary": "The Best"},
    {"asin": "B0000CCZYY", "reviewerName": "Mary E. Copper \"meca\"", "reviewText": "I often buy this licorice at the health food store and it's expensive, but with the add on item program, I can tuck it into other purchases and get a great price.  So if you want the real thing a a great price, tuck it into the cart and get a bargain.", "overall": 5.0, "summary": "Real Licorice Real Tasty"},
    {"asin": "B0000CCZYY", "reviewerName": "R", "reviewText": "Panda licorice, There is not too much I can say about panda licorice It's very good that's why I keep on buying it.", "overall": 5.0, "summary": "Panda licorice"},
    {"asin": "B0000CCZYY", "reviewerName": "The Kittie \"Kittie\"", "reviewText": "This is an awesome product, natural, not a lot of ingredients, good flavor, not too sweet.But I no longer love our scaredy-cat friends at Amazon! :PNow they won't let you write honest reviews of the product, so lame.What's insane is the price! I can easily get this same thing at the grocery store for 1/3 to 1/2 the price (not even on sale).But here it's at a greatly inflated rate AND they've made it an \"add-on\" item - shameful.Add-on is the worst new \"feature\" I've seen in the many, many years that I've been shopping at this site.I am a Prime member & signed up for that so I could get FREE shipping on ANY item at ANY time - not so I would STILL have to group items into $25 & higher orders. Pathetic. Way to go Amazon. :PBUT - this is ABSOLUTELY the best licorice out there! Just be careful if you have high blood pressure: it uses real licorice as the main flavoring & licorice root can increase a person's blood pressure.OK, Amazon, will you chicken out & block my review again??", "overall": 1.0, "summary": "Love this candy!"},
    {"asin": "B0000CDBQN", "reviewerName": "amazon buyer", "reviewText": "i use this on every pizza i have!sweet and spicy and goes good with the sweetness of the pizza sauce.i use the green version on white sauce pizza's :-)", "overall": 5.0, "summary": "love this!!!"},
    {"asin": "B0000CDBQN", "reviewerName": "Amazon Customer", "reviewText": "Just a little is needed to get the full effect.  This seasoning blend is spicy hot, just like the label states.  It still tastes good, like the more mild version, but it has a definite kick to it.  What I like to do is mix the two, this one and Chef Paul Prudhomme's Magic Seasoning Blends ~ Pizza & Pasta Magic Herbal.  That way it is not too intense for me.", "overall": 5.0, "summary": "A recomended spicy hot blend"},
    {"asin": "B0000CDBQN", "reviewerName": "Don", "reviewText": "I've commented on other spices from Chef Paul Prudhomme in the past. His all have great quality and spice mixture.", "overall": 5.0, "summary": "Great Brand"},
    {"asin": "B0000CDBQN", "reviewerName": "jjceo", "reviewText": "This is a great product to accent your pizza and pasta sauces without adding the things you don't want into your diet!  It is a little bit hot as a seasoning and you can also sprinkle it onto spaghetti or pizza.  It is also very good when sprinkled onto casseroles or soups.  I like it as it has no calories, no total fat, no sodium, no carbohydrates and no additional protein.  It also contains no MSG or any preservatives.It lets you add the zest you like without adding items like salt or calories.  This is a good product and we like it as a seasoning for many of our Italian dishes.  I recommend it to you as a good product.", "overall": 5.0, "summary": "Calling it Magic doesn't do it justice!"},
    {"asin": "B0000CDBQN", "reviewerName": "Susanna K. Robbins Ttee", "reviewText": "This is such a fantastic product - I use it all the time and will continue to order it.  Thank you, Paul Prudhomme!", "overall": 5.0, "summary": "FANTASTIC"},
    {"asin": "B0000CETGM", "reviewerName": "J. Hesse", "reviewText": "Jamaica Blue Mountain Coffee is my absolute favorite coffee.  It has a nice rich taste and a super smooth texture.  I have yet to find a coffee that I like near as much.  That being said, I bought my Blue Mountain Coffee in Jamaica...not online...so I can't vouch for the quality/freshness here.", "overall": 5.0, "summary": "My favorite coffee"},
    {"asin": "B0000CETGM", "reviewerName": "Jim at Lansing \"Amazon is great, and offers g...", "reviewText": "The coffee does have a production date and best/use by date. Maybe I am the only one, but my purchase came back as quite close to the use by date, so just be careful. The coffee is good.", "overall": 3.0, "summary": "Be aware of this produce"},
    {"asin": "B0000CETGM", "reviewerName": "J T Cannon Jr", "reviewText": "So many coffee enthusiasts come back to Blue Mountain time and time again as one of the finest coffees you can find in the world.  This is so delicious it won't last long.", "overall": 5.0, "summary": "The Best in the World"},
    {"asin": "B0000CETGM", "reviewerName": "Michael A. Duvernois", "reviewText": "I mean this stuff was roasted how long ago? A far lesser coffee roasted a couple of days ago is going to taste a whole lot better. At $50 per pound, what you're tasting is justification for spending the money. What you should do, if you have the money for this sort of coffee, is buy a coffee roaster and start getting good green beans (including Jamaican Blue Mountain) and roasting them fresh yourself. The folks at Sweet Maria's have all the info you need to get started.", "overall": 3.0, "summary": "Decent coffee, but ridiculously priced for not fresh coffee"},
    {"asin": "B0000CETGM", "reviewerName": "talonmedic", "reviewText": "First a little background on me. I Am a coffee drinking fiend. I probably keep several countries coffee production up, so I know coffee. I don't mind strong coffee or so so tasting coffee I just dont expect it to be expensive so so tasting coffee. I have had and love Jamaican Blue mountain coffee before but it was a lot more expensive than this. This came in a cute little burlap sack (you get some style points there) but after that it's pretty much down hill. The coffe is not the normal rich tasting wonderfull smelling JBM I have had before, it just tastes like every other coffee albeit at an extravagent price. I have ordered some more Blue mountain from another supplier will have to see how that goes. This is one that will not get any repeat business from me. There are plenty of other better tasting coffees out there at a lower price.", "overall": 3.0, "summary": "Not worth it for the money"},
    {"asin": "B0000CNU15", "reviewerName": "Chi-Chi Loves Amazon \"Chi Chi the magic chihu...", "reviewText": "I love this stuff! It is great in dipping sauces. I also like this in my chicken soup broth or pretty much any soup. I wouldn't think of eating Ramen noodles normally but with some of this stuff, I will eat it and like it. I think it is better than Schriacha sauce, you just have to be careful and use a small amount till you know how strong it is and then you will be adding  it to everything. I do a quick dipping sauce with soy sauce, vinegar, sugar and this oil. Great for dumplings! This is a staple that everyone should have in kitchen.", "overall": 5.0, "summary": "Chi Chi likes it hot!"},
    {"asin": "B0000CNU15", "reviewerName": "hba864", "reviewText": "I got this specifically to make dan dan noodles, and it was perfect! the chunky bits of chili are so good I use this when I make chinese stir frys too. its really spicy but not omg my mouth..its a smoother spicy if that makes any sense lol", "overall": 5.0, "summary": "yum!"},
    {"asin": "B0000CNU15", "reviewerName": "Jeffrey Pittman \"Jeff\"", "reviewText": "My favorite nearby Asian food mart is closing with plans to reopen months from now in a new location.  I need this stuff badly as a staple that must always be in stock, but I don't need it badly enough to pay nearly twice what it costs in a retail store, plus nearly double that again to have it sent to me.  I love Amazon so I hate it when Amazon is the worst possible place to buy a product, but there it is.I will look around for other sources because this stuff is AWESOME.  It has more fire than the relatively wimpy chili oils in the ethnic sections of mainstream US grocery stores, but you can control the burn factor by choosing how much to use in your recipe or as a condiment.  The flavor is subtle and isn't overbearing even if you load it on to increase the heat.  Very versatile and very good.", "overall": 5.0, "summary": "Great stuff, but just STUPID expensive here unfortunately"},
    {"asin": "B0000CNU15", "reviewerName": "Mike Tarrani \"Jazz Drummer\"", "reviewText": "Although many folks cook with this oil I use it as a condiment. I love the way the spicy heat builds and spreads, and the subtle and not-so-subtle flavors that you can taste. Also, it is salty enough to use as a substitute for salt the same way you would with soy sauce or a fish sauce.A little goes a long way, and especially if you are counting calories, fat or sodium intake. A serving is about a teaspoon - more than enough to mix into rice or drizzle over other dishes - and it comes in at 90 calories. That same serving contains 9 grams of fat and 440mg of sodium. So, do use sparingly if you are watching any of those nutritional factors.Another thing that I personally love is this is unfiltered. There are pieces of peppers and other ingredients that will suspend in the oil if you vigorously shake the jar before serving. Those add a lot to the flavor profile, which is predominately salty and piquant (and there is also a distinct element of umami).If you love spicy sauces and oils and want to 'spice' up your meal (pun intended) this is an excellent infused oil that will do the trick. I wish I could elaborate on how it works for sir frying, but I do not use it that way. I can say that it is an excellent condiment.", "overall": 5.0, "summary": "Amazing as a condiment"},
    {"asin": "B0000CNU15", "reviewerName": "R. Billings", "reviewText": "I ordered this to use in Asian cooking and have not yet had a chance to use it in a recipe.  However I did sample it and seems like it will add some spice as needed.", "overall": 5.0, "summary": "Lee Kum Kee Chiu Chow Chili Oil"}

  ], 
  products: [
    {'asin': '9742356831', 'category': 'Condiments and Seasonings', 'description': 'Used to make various curry soups and stir fry dishes. Mae Ploy Brand is recognized in Thailand as a high quality export product with rich taste and authentic flavor. Packed in convenient plastic tub with tighly sealed lid. All natural.', 'title': 'Mae Ploy Thai Green Curry Paste - 14 oz jar', 'price': 7.23, 'imUrl': 'http://ecx.images-amazon.com/images/I/41pQp67A7rL._SX300_.jpg'},
    {'asin': '616719923X', 'category': 'Candy', 'description': "Green Tea Flavor Kit Kat have quickly become the most sought after snack from Japan. Here are a limited supply of Maccha Green Tea flavored Kit Kat that you would not want to miss. These epic snacks have a sweet maccha green tea flavor mixed with creamy white chocolate, on a crispy wafer that Nestle's has perfected. Each bag contains 12 individually wrapped bars.", 'title': 'Japanese Kit Kat Maccha Green Tea Flavor (5 Bag) (4.91oz x 5)', 'price': 10.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/51LdEao6%2B8L._SX300_.jpg'},
    {'asin': 'B0000CCZYY', 'category': 'Candy', 'description': 'Licorice (Black) Chews by Panda Licorice 7 oz Box PANDA ALL NATURAL - THE REAL TASTE OF LICORICE The strong-flavoured high-quality Panda All Naturall Licorice is the Rolls Royce of licorices. The product is manufactured from natural ingredients without preservatives and using time-honoured manufacturing methods. It forms a natural alternative for those with a passion for licorice and has been the most successful all natural licorice in the world since 1977 as the market leader in its sector of the Health Food Industries in Great Britain and the United States. Panda - A fresh success Panda Licorice comes in a package that has been developed specifically to keep the product soft fresh and delicious tasting. Pandas success around the world is based on the freshness and unique consistency of the product. The unique Real taste of Licorice Premium quality soft licorice All Natural ingredients No added colours No added salt No artificial flavours 99 fat free No preservatives Kosher certified', 'title': 'Panda All Natural Soft Licorice 7 oz Pkg', 'price': 6.79, 'imUrl': 'http://ecx.images-amazon.com/images/I/51%2B2k2EclFL._SY300_.jpg'},
    {'asin': 'B0000CDBQN', 'category': 'Condiments and Seasonings', 'description': 'Chef Paul Prudhommes Magic Seasoning Blends has been in business since 1982 when customers from Chef Pauls New Orleans-based K-Pauls Louisiana Kitchen restaurant began asking to take home the chefs unique seasonings. What was once a garage-housed operation has grown to a 50,000 square-foot plant. Currently, Magic Seasoning Blends offers all-natural, MSG free products in sixteen different blends; Magic Pepper Sauce; seven ground, dried Magic Chiles; four Magic Sauce & Marinades; and several cookbook gift-packs. With the exception of Pizza & Pasta seasonings and the sauce/marinades, all products are certified Kosher.', 'title': "Chef Paul Prudhomme's Magic Seasoning Blends ~ Pizza &amp; Pasta Magic Hot &amp; Sweet, 3.6-Ounce Bottle", 'price': 3.5, 'imUrl': 'http://ecx.images-amazon.com/images/I/41RRpfr9vuL._SY300_.jpg'},
    {'asin': 'B0000CETGM', 'category': 'Tea and Beverages', 'description': 'Jamaica Blue Mountain Coffee 1Lb. Bag (also called Jamaica Blue Mountain Wallenford Estate Coffee) - Jamaica Blue Mountain coffee is one of the most sought after coffees in the world. This "Java of Kings" has been satisfying coffee connoisseurs around the globe for more than two centuries and is famous for its exquisite flavor, good acidity, a clean refined taste,unusual sweetness, excellent body and intense bold aroma. This extraordinary coffee is grown in the majestic Blue Mountain range in Jamaica reaching approximately 7,402 feet at the highest peak, thus making it is one of the highest grown coffees in the world.', 'title': 'Jamaica Blue Mountain Coffee , Certified 100% Pure, Roasted Beans in a 1lb Sac', 'price': 52.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/41nuZYbTwAL._SX300_.jpg'},
    {'asin': 'B0000CNU15', 'category': 'Condiments and Seasonings', 'description': 'An authentic hot chili sauce originated in Chiu Chow, China. Prepared from the finest preserved chili, this sauce is hot!', 'title': 'Lee Kum Kee Chiu Chow Chili Oil', 'price': 7.09, 'imUrl': 'http://ecx.images-amazon.com/images/I/51YAihJnRLL._SY300_.jpg'},
    {'asin': '3301261876', 'category': 'Candy', 'description': 'A tub of 600 Haribo fruit flavoured Jelly Babies', 'title': 'Haribo Jelly Babies Gummy Sweets', 'price': 25.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/51Hh-%2BOW9NL._SY300_.jpg'},,
    {'asin': '3295000018', 'category': 'Condiments and Seasonings', 'description': 'Kiva Gourmet Ghost Chili Pepper Powder:Made from one of the hottest peppers \non earth, this bottle contains 100% \npure ghost chili pepper powder (also known as Bhut Jolokai).  Our peppers are \nsmoked dried to give them its unique \nhot and smokey flavor.  Packed in wide mouth glass jar for easier access. 2 oz size.Use very sparingly as a little bit goes \na long way to add spice and flavor to \nchili, sauces, dips, meats, vegetables, etc.About Kiva:At Kiva, we strive to provide you with innovative food from around the world that is great tasting, healthy and of the highest quality.  We are committed to using only ingredients that are sourced directly from local farmers that practice sustainable and eco-friendly methods.', 'title': 'Kiva Gourmet Smoked, Ghost Chili Pepper Powder (Bhut Jolokia) - Wide Mouth Jar', 'price': 14.80, 'imUrl': 'http://ecx.images-amazon.com/images/I/41LsMz6S5oL._SY300_.jpg'},
    {'asin': 'B0000631X2', 'category': 'Candy', 'description': 'JELLY BELLY PET DINOSAUR 24 COUNT', 'title': 'Jelly Belly Gummi Dinosaur, 1.75-Ounce Packages (Pack of 24)', 'price': 39.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/41YVD6M27SL._SY300_.jpg', 'related': {'also_viewed': ['B000IKDIEW', 'B00916CJV2', 'B003EMU77W', 'B001M2FNH0', 'B00C6BY7Y6', 'B002I57NL4', 'B009EVMRVQ', 'B00JK4QDBM']}},
    {'asin': 'B00009WDTB', 'category': 'Candy', 'description': 'The people behind Auburn, Calif.-based Sharkies want the best for their bodies and minds and they believe you do, too! "Our goal is to provide healthy, great tasting snacks that fit an active lifestyle."Why Sharkies?What are naturally occuring electrolytes?The naturally occurring electrolytes in Sharkies&#xA8; come from the potassium in the fruit juice and the sodium in the rice and water. These are not the commercial electrolytes currently used in most products claiming to have electrolytes. The source of most of those electrolytes is sodium citrate and potassium phosphate. This makes them commercially processed and generally low quality.Isn\'t Sharkies just a candy product?Although children can and will consume Sharkies as a "better for you" candy, none of the sugars in Sharkies are refined and half the product is rice syrup giving it complex carbohydrates for sustained energy. This added to the simple sugars from the fruit and organic cane make Sharkies a functional, healthy alternative to candy. Unlike candy, Sharkies doesn\'t contain high fructose corn syrup, sucrose, or further refined sugar.What\'s the difference between Sharkies and gummy bears?No gelatin and no refined sugars are found in Sharkies. Complex carbohydrates make up half of the ingredients, which keep children and athletes from "sugar crashing" and sustains energy.Why are they called organic energy fruit chews?The grape juice, which is a simple sugar, offers a quick burst of energy and the brown rice syrup is a complex carbohydrate, which offers longer sustained energy. The electrolytes allow for the absorption of water in the cells and keep your body hydrated.What is a black carrot?It\'s really more of a dark purple color but called a black carrot. It is the raw material of turnip salgum juice a natural color used in Sharkies.', 'title': 'Sharkies Organic Energy Sports Chews, Mixed Berry, 1.58-Ounce Bags (Pack of 12)', 'price': 21.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/21XAP2KCVJL.jpg'},
    {'asin': 'B0000BVOI6', 'category': 'Condiments and Seasonings', 'description': "A blend of salt and spices for the rim of your 'rita. The Margarita, one of the world's most festive drinks, is not libation - it's a lifestyle! We've taken some creative license with the margarita's traditional salt rim and imparted lots of south-of-the-border savor to our sensational Rimmer. The drink from the lad-back land of manana never sipped more smoothly. Made in USA.", 'title': 'Stirrings Margarita Drink Rimmer, 3.5-Ounce Tin (Pack of 6)', 'price': 29.85, 'imUrl': 'http://ecx.images-amazon.com/images/I/51C02K3CN2L._SY300_.jpg'},
    {'asin': 'B0000C69FB', 'category': 'Tea and Beverages', 'description': 'Tazo Awake blends the dense, malty flavor of teas from Assam, near the Burma border in Northeast India, with bright, full-flavored Dimbula teas from Ceylon. The result is a perfectly balanced breakfast tea, robust and delicious enough to drink all day long.Black teas are made from the fully fermented leaf of the Camellia sinensis and contain caffeine. Tazo Premium black teas are grown at high elevations for the best flavor and then plucked by hand. The leaves are then crushed and tightly rolled into wiry threads to release an enzyme that, when exposed to oxygen, begins the fermentation process. They are then dried by oven firing, creating the malty, rich flavors and amber color that have been characteristic of black tea for thousands of years.Unlike other tea companies, Tazo purchases teas in their original container as packed at the garden to ensure the tea inside the chest or bag stays garden fresh and is not exposed to the heat and moisture in a blending facility at one of the tea shipping points.Label InformationIngredientsA Blend of Black Teas from India and Ceylon. Contains caffeine.', 'title': 'Tazo Awake Black Tea, 24-Count Tea Bags (Pack of 6)', 'price': 6.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/51YRWG712RL._SY300_.jpg'},
    {'asin': 'B0000C69GA', 'category': 'Tea and Beverages', 'description': 'A crisp, refreshing blend of premium black teas with subtle citrus notes.Fresh brewed Tazo Iced Teas. It\'s probably why ice was created in the first place. Tazo is made from the most extraordinary teas and herbs found anywhere and blended with an artistry that borders on magical. Tazo fresh brewed iced teas are now available in four refreshing flavors. Each filterbag brews one gallon.Tazo was created for one purpose: to reinvent tea and the tea experience.  By using high quality ingredients and a tremendous amount of experience and creativity, Tazo has produced unique products that create an emotional connection with the consumer at many levels.  Tazo continues to expose consumers to the ancient traditions of tea, but presents this in a way that is bold, interesting and intriguing.Unlike other tea companies, Tazo purchases teas in their original container as packed at the garden to ensure the tea inside the chest or bag stays garden fresh and is not exposed to the heat and moisture in a blending facility at one of the tea shipping points.The blending process is a very subtle art form that relies on subjective measurement of taste, color and aroma.  Tazo constantly taste and determine which teas will go in which blend in what percentage, so flavor profiles remain consistent and of the highest quality possible.The name Tazo has roots in many civilizations. Tazo actually means "river of life" in the Romany Gypsy language and was used as a toast to life by ancient Greeks. Tazo also means "fresh" in several Hindi dialects. In ancient Babylonia, Tazo was a rejuvenating elixir thought to have magical properties.Tazo is kosher certified by KSA.', 'title': 'Tazo Iced Black Tea Filterbags, 1-1/4-Ounce Filterbags (24-Count Total)', 'price': 3.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/41H2DQS8MXL._SY300_.jpg'},
    {'asin': 'B0000C69FO', 'category': 'Tea and Beverages', 'description': 'An invigorating blend of Northwest grown mint and other fragrant botanicals.Tazo was created for one purpose: to reinvent tea and the tea experience.  By using high quality ingredients and a tremendous amount of experience and creativity, Tazo has produced unique products that create an emotional connection with the consumer at many levels.  Tazo continues to expose consumers to the ancient traditions of tea, but presents this in a way that is bold, interesting and intriguing.Unlike other tea companies, Tazo purchases teas in their original container as packed at the garden to ensure the tea inside the chest or bag stays garden fresh and is not exposed to the heat and moisture in a blending facility at one of the tea shipping points.The blending process is a very subtle art form that relies on subjective measurement of taste, color and aroma.  Tazo constantly taste and determine which teas will go in which blend in what percentage, so flavor profiles remain consistent and of the highest quality possible.The name Tazo has roots in many civilizations. Tazo actually means "river of life" in the Romany Gypsy language and was used as a toast to life by ancient Greeks. Tazo also means "fresh" in several Hindi dialects. In ancient Babylonia, Tazo was a rejuvenating elixir thought to have magical properties.Tazo is kosher certified by KSA.', 'title': 'Tazo Refresh Herbal Tea Filterbags with Dispenser, Six (6) 24-Count Filterbags (144 Bags Total)', 'price': 28.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/51252R6G7FL._SX300_.jpg'},
    {'asin': 'B0000C69FK', 'category': 'Tea and Beverages', 'description': 'Green tea with natural lotus flower flavor.      Tazo was created for one purpose: to reinvent tea and the tea experience.  By using high quality ingredients and a tremendous amount of experience and creativity, Tazo has produced unique products that create an emotional connection with the consumer at many levels.  Tazo continues to expose consumers to the ancient traditions of tea, but presents this in a way that is bold, interesting and intriguing.     Unlike other tea companies, Tazo purchases teas in their original container as packed at the garden to ensure the tea inside the chest or bag stays garden fresh and is not exposed to the heat and moisture in a blending facility at one of the tea shipping points. &lt;p&gt; The blending process is a very subtle art form that relies on subjective measurement of taste, color and aroma.  Tazo constantly taste and determine which teas will go in which blend in what percentage, so flavor profiles remain consistent and of the highest quality possible.     The name Tazo has roots in many civilizations. Tazo actually means "river of life" in the Romany Gypsy language and was used as a toast to life by ancient Greeks. Tazo also means "fresh" in several Hindi dialects. In ancient Babylonia, Tazo was a rejuvenating elixir thought to have magical properties.     Tazo is kosher certified by KSA.', 'title': 'Tazo Tea Filter Bags, China Green Tip', 'price': 5.18, 'imUrl': 'http://ecx.images-amazon.com/images/I/513QXS5Y0XL._SX300_.jpg', 'brand': 'TAZO'},
    {'asin': 'B0000C69G3', 'category': 'Tea and Beverages', 'description': 'Exotic floral and nutty notes with a pungent fresh flavor, capturing the essence of the Himalayas.Tazo was created for one purpose: to reinvent tea and the tea experience.  By using high quality ingredients and a tremendous amount of experience and creativity, Tazo has produced unique products that create an emotional connection with the consumer at many levels.  Tazo continues to expose consumers to the ancient traditions of tea, but presents this in a way that is bold, interesting and intriguing.Unlike other tea companies, Tazo purchases teas in their original container as packed at the garden to ensure the tea inside the chest or bag stays garden fresh and is not exposed to the heat and moisture in a blending facility at one of the tea shipping points.The blending process is a very subtle art form that relies on subjective measurement of taste, color and aroma.  Tazo constantly taste and determine which teas will go in which blend in what percentage, so flavor profiles remain consistent and of the highest quality possible.The name Tazo has roots in many civilizations. Tazo actually means "river of life" in the Romany Gypsy language and was used as a toast to life by ancient Greeks. Tazo also means "fresh" in several Hindi dialects. In ancient Babylonia, Tazo was a rejuvenating elixir thought to have magical properties.Tazo is kosher certified by KSA.', 'title': 'Tazo Darjeeling Organic Tea Filterbags with Dispenser, Six (6) 24-Count Filterbags (144 Bags Total)', 'price': 18.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/511QTS6HKYL._SX300_.jpg'},
    {'asin': 'B0000CAV3B', 'category': 'Tea and Beverages', 'description': 'Coffee Cairo is Turkish coffee, spiced with cardamom and cloves, a blend closer to the first coffee of the 16th and 17th centuries. They drink it this way in most of the Middle East, in Middle Eastern restaurants in America, and of course, in Cairo.', 'title': 'Cairo Turkish Style Coffee 1lb Bag', 'price': 16.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/5125VFYH57L._SY300_.jpg'},
    {'asin': 'B0000CAV3A', 'category': 'Tea and Beverages', 'description': 'Our quest for exotic coffees led us to the grandmother of all spices -- coriander, probably one of the first spices used by mankind, having been known as early as 5000 BC. While cardamom is the most predominant spice added to Turkish coffee in the Middle East, coriander is the preferred spice for many North Africans. Berber Coffee is our own blend of the finest Central American coffees, freshly ground with fresh coriander added.', 'title': 'Berber Turkish Style Coffee .5lb Bag', 'price': 10.50, 'imUrl': 'http://ecx.images-amazon.com/images/I/5125VFYH57L._SY300_.jpg', 'related': {'also_bought': ['B0000CAV3C'], 'also_viewed': ['B000CCMSSI']}},
    {'asin': 'B0000CDBQ5', 'category': 'Condiments and Seasonings', 'description': 'These Ground Dried Magic Chiles are the most commonly used dried chiles in Mexico. They are wonderful additions to soups, sauces and gravies. Use a small amount to add excitement to any dish, even desserts. Adding the milder chiles will provide a pleasant chile flavor without adding heat.Chef Paul Prudhommes Magic Seasoning Blends has been in business since 1982 when customers from Chef Pauls New Orleans-based K-Pauls Louisiana Kitchen restaurant began asking to take home the chefs unique seasonings. What was once a garage-housed operation has grown to a 50,000 square-foot plant. Currently, Magic Seasoning Blends offers all-natural, MSG free products in sixteen different blends; Magic Pepper Sauce; seven ground, dried Magic Chiles; four Magic Sauce & Marinades; and several cookbook gift-packs. With the exception of Pizza & Pasta seasonings and the sauce/marinades, all products are certified Kosher.', 'title': "Chef Paul Prudhomme's Magic Seasoning Blends ~ Chipotle Ground Dried Magic Chile, 1.5-Ounce Bottle", 'price': 3.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/4138TA4CHML._SY300_.jpg', 'related': {'also_bought': ['B0000CDBQ9', 'B0000CDBQ7', 'B0000CDBQ6', 'B0000CDBRH'], 'also_viewed': ['B0000CDBPV', 'B0000CDBQB', 'B0000CDBPL', 'B0000CDBPT'], 'bought_together': ['B0000CDBQ7']}},
    {'asin': 'B0000CEUF9', 'category': 'Condiments and Seasonings', 'description': "Pacifica Culinaria's Coastal Lemon Avocado Oil Vitamin rich, cholesterol free Avocado oil with fresh zesty lemon oil to offer the perfect complement to your culinary creations. Drizzle over salads, brush on for grilling or substitute in recipes for a tasty and healthier choice. 8.5 oz (250mL) glass bottle", 'title': "Pacifica Culinaria's Coastal Lemon Avocado Oil", 'price': 11.50, 'imUrl': 'http://ecx.images-amazon.com/images/I/31OIRgj5fLL._SY300_.jpg', 'related': {'also_bought': ['B0000CEUF8'], 'bought_together': ['B0000CEUF8']}},
    {'asin': 'B0000CGD6Y', 'category': 'Seafood', 'description': 'Premium, gourmet Chesapeake Bay crab cakes lovingly made with just the right spices and our finest hand-picked Maryland lump crabmeat. Our mouth-watering crab cakes are handmade at our facility in Crisfield, Maryland, "the crab capitol of the world." They are made from the finest local Maryland lump crabmeat and contain only enough filler to hold the meat together. You are just a click away from being able to enjoy our Lump Maryland Crab Cakes in the comfort of your own home.', 'title': 'The Crab Place 2 oz. Maryland Jumbo Lump Crab Cakes, 1 Dozen', 'price': 39.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/41MQ073H7VL._SX300_.jpg'},
    {'asin': 'B0000CNU2G', 'category': 'Condiments and Seasonings', 'description': 'Wasabi Fumi Furikake Rice Seasoning', 'title': 'Wasabi Fumi Furikake Rice Seasoning', 'price': 4.65, 'imUrl': 'http://ecx.images-amazon.com/images/I/31Mdu5%2BV18L.jpg', 'brand': ''},
    {'asin': 'B0000CNU2N', 'category': 'Seafood', 'description': 'Light and crispy fried Shrimp Chips are great for appetizers or snacking. Serve plain or with sweet & sour sauce. Assorted colors. Store unused chips in airtight container...will store indefinitely if kept dry.', 'title': 'Welpac Shrimp Flavored Chips', 'price': 5.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/51KRwAh7SEL._SY300_.jpg'},
    {'asin': 'B0000CNU08', 'category': 'Condiments and Seasonings', 'description': 'Sweet and delicate Dynasty Lychees add an exotic touch to fruit or vegetable salads. Serve chilled for a perfect Oriental dessert. Or use Dynasty Lychees as a topping for your favorite ice cream.', 'title': 'Dynasty Peeled Whole Lychees', 'price': 9.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/51RTFruKq2L._SY300_.jpg'},
    {'asin': 'B0000CNU6T', 'category': 'Condiments and Seasonings', 'description': 'Lee Kum Kee Honey Garlic is made from first grade garlic and the finest honey. It is a ready-to-use sauce for baking, grilling, and stir-frying.', 'title': 'Lee Kum Kee Honey Garlic Sauce', 'price': 11.42, 'imUrl': 'http://ecx.images-amazon.com/images/I/41hohU1FKhL._SY300_.jpg'},
    {'asin': 'B0000CNTSH', 'category': 'Seafood', 'description': 'Maryland blue crabs are undeniably the Bay\'s most sought after food. "Crab Feast" is the featured event at summer festivals all over the State. For your crab feast we ship the freshest hard crabs available. Order them steamed and seasoned with J.O. Brand seasoning or live. Live crabs are shipped UPS Next Day Air only. Steamed hard crabs cannot be sent using UPS 2-Day Air.', 'title': 'Select Male Hard Crabs (Steamed), 1 Dozen', 'price': 59.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/31N8VA61D5L.jpg'},
    {'asin': 'B0000CNU4H', 'category': 'Condiments and Seasonings', 'description': 'Hot sauce made with chiles and spices, also called Mexican salsa picante. Bufalo Classica style. Mexico s favorite hot sauce.', 'title': 'Bufalo Salsa Picante Clasica - Hot - 5.7 oz (Pack of 3)', 'price': 13.50, 'imUrl': 'http://ecx.images-amazon.com/images/I/31xXpk95UwL._SY300_.jpg'},
    {'asin': 'B0000D16IO', 'category': 'Condiments and Seasonings', 'description': "Chutney's sweet spiciness is the perfect condiment for hot Indian curries This chunky mango version is fruity, somewhat peppery in flavor, dark orange in color, and hot to the palate. Serve with grilled meat, add to curries, spread on crackers or toast.", 'title': 'Hot Mango Chutney', 'price': 14.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/11A0DEQJGKL.jpg'},
    {'asin': 'B0000D17D4', 'category': 'Condiments and Seasonings', 'description': 'This extra-virgin olive oil for the Provence region of southern France is a sensual treat. With a deep, greenish-gold color, medium-bodied texture, and mild vegetal aroma, it has a pronounced herbal character with a pleasantly astringent peppery sharpness. Use when you want a pronounced olive taste, such as a dip for crusty warm bread, to dress a fresh tomato salad, or tossed with fresh pasta and parmesan cheese.', 'title': "Huile D'Olive Vierge Extra", 'price': 25.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/11E2KGG3T1L.jpg'},
    {'asin': 'B0000D198R', 'category': 'Condiments and Seasonings', 'description': 'A clear vinegar (su) made from fermented rice, this vinegar adds a tangy taste to many Japanese salad dressings, marinades, and dipping sauces. Use the seasoned variety (sushi-su) for sushi.', 'title': 'Japanese Rice Wine Vinegar Unseasoned', 'price': 7.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/11BSJP3J1ML.jpg', 'related': {'also_viewed': ['B004NXR92C', 'B0033I91TM']}},
    {'asin': 'B0000D91K5', 'category': 'Seafood', 'description': 'Lobster tail is the sweetest part of the lobster with the biggest portion of meat. Cooked lobster meat should be pure white, opaque and elastic. See if you can pull the tail meat out in one large piece! Serve it with melted butter and lots of cloth napkins and warm water. Lobster tails are shipped fresh from New England in 6-7 ounce, 8-10 ounce and 12-14 ounce sizes.', 'title': 'The Crab Place Lobster Tails (6-7 oz.), Each', 'price': 40.00, 'imUrl': 'http://ecx.images-amazon.com/images/I/21PW8T6J2BL.jpg'},
    {'asin': 'B0000D8HDS', 'category': 'Candy', 'description': 'Chocolate biscotti with mini chocolate chips, and whole almonds---luscious! Frosted with milk chocolate.', 'title': '8 pieces Milk Chocolate Frosted CHOCOLATE ALMOND Biscotti', 'price': 8.75, 'imUrl': 'http://ecx.images-amazon.com/images/I/413G6TT9TGL._SX300_.jpg'}
  ]
};

db.sync({force: true})
.then(function () {
  console.log("Dropped old data, now inserting data");
  const creatingReviews = Promise.map(data.reviews, function(review) {
    return Review.create(review);
  });
  const creatingProducts = Promise.map(data.products, function(product) {
    return Product.create(product, {include: [Related]});
  });
  return Promise.all([creatingReviews, creatingProducts]); // if more tables needed
})
.then(function () {
  console.log('Finished inserting data');
})
.catch(function (err) {
  console.error('There was totally a problem', err, err.stack);
})
.finally(function () {
  db.close(); // creates but does not return a promise
  return null; // stops bluebird from complaining about un-returned promise
});